- name: BACKUP PLAYBOOK
  hosts: localhost
  tasks:
    - name: Include vars
      include_vars:
        file: vars.yml
    - name: ensure no old version of cron job
      k8s:
        state: absent
        api_version: batch/v1beta1
        kind: CronJob
        name: "pg-backup-cronjob-{{ meta.name }}"
        namespace: "{{ meta.namespace }}"