- name: get database info
  include_role:
    name: database
    tasks_from: get_info
  vars:
    res_key: "from_database"
    database_name: "{{ from_database_name }}"
- name: get az blobs container info
  include_role:
    name: database
    tasks_from: get_info
  vars:
    res_key: "to_database"
    database_name: "{{ to_database_name }}"
- name: get vars
  set_fact:
    from_database: "{{ res_dict.from_database }}"
    to_database: "{{ res_dict.to_database }}"
    after_action_database: "{{ res_dict.to_database }}"
- name: get pg_restore container info
  include_role:
    name: jobs
    tasks_from: container_def_pg_restore
- name: get pg_dump container info
  include_role:
    name: jobs
    tasks_from: container_def_pg_dump
- debug:
    var: pg_restore_container
- debug:
    var: pg_dump_container
- name: create job spec
  include_role:
    name: jobs
    tasks_from: create_job_spec
  vars:
    from_container: "{{ pg_dump_container }}"
    to_container: "{{ pg_restore_container }}"
- debug:
    var: job_type
- name: create job
  include_role:
    name: jobs
    tasks_from: "create_{{ job_type }}"
