- name: ensure scripts
  include_role:
    name: jobs
    tasks_from: ensure_scripts
- name: create cron job
  k8s:
    state: "{{ desired_state }}"
    definition:
      apiVersion: batch/v1beta1
      kind: CronJob
      metadata:
        name: "pg-backup-{{ job_action }}-{{ meta.name }}"
        namespace: "{{ meta.namespace }}"
      spec:
        schedule: "{{ cron_interval }}"
        jobTemplate:
          spec: "{{ job_spec }}"