- debug:
    var: meta
- debug:
    var: job_spec
- name: generate random name
  set_fact:
    job_name: "pg-backup-job-{{ meta.name }}-{{ ansible_date_time.epoch | string | b64encode | regex_replace('=+', '') | lower }}"
- name: ensure scripts
  include_role:
    name: jobs
    tasks_from: ensure_scripts
  when: desired_state == "present"
- name: create job
  k8s:
    state: "{{ desired_state }}"
    definition:
      apiVersion: batch/v1
      kind: Job
      metadata:
        name: "{{ job_name }}"
        namespace: "{{ meta.namespace }}"
      spec: "{{ job_spec }}"
  when: desired_state == "present"

