- name: create job
  k8s:
    state: present
    definition:
      apiVersion: batch/v1
      kind: Job
      metadata:
        name: pg-backup
        namespace: "{{ meta.namespace }}"
      spec:
        backoffLimit: 3 # max try 3 times
        template:
          spec:
            restartPolicy: Never
            initContainers:
              - "{{ from_container }}"
            containers:
              - "{{ to_container }}"
            volumes:
              - name: scripts
                configMap:
                  name: pg-backup-scripts
                  defaultMode: 0777
              - emptyDir: {}
                name: pgdump

