- name: ensure no old version of cron job
  k8s:
    state: absent
    definition:
      apiVersion: batch/v1beta1
      kind: CronJob
      metadata:
        name: pg-backup-cronjob
        namespace: "{{ meta.namespace }}"
# doing this at the same point in time that create_job does it
- name: ensure scripts
  include_role:
    name: jobs
    tasks_from: ensure_scripts
- name: create cron job
  k8s:
    state: present
    definition:
      apiVersion: batch/v1beta1
      kind: CronJob
      metadata:
        name: pg-backup-cronjob
        namespace: "{{ meta.namespace }}"
      spec:
        schedule: "{{ cron_interval }}"
        jobTemplate:
          spec: "{{ job_spec }}"
