#- debug:
#    var: job_spec
- name: generate name
  set_fact:
    job_name: "pg-{{ job_action }}-job-{{ meta.name }}"
- name: ensure scripts
  include_role:
    name: jobs
    tasks_from: ensure_scripts
- name: create job
  k8s:
    apply: yes
    state: present
    definition:
      apiVersion: batch/v1
      kind: Job
      metadata:
        name: "{{ job_name }}"
        namespace: "{{ meta.namespace }}"
      spec: "{{ job_spec }}"
