- name: ensure no old version of backup job
  k8s:
    state: absent
    definition:
      apiVersion: batch/v1
      kind: Job
      metadata:
        name: pg-backup
        namespace: "{{ meta.namespace }}"
- name: create job
  k8s:
    state: present
    definition:
      apiVersion: batch/v1
      kind: Job
      metadata:
        name: pg-backup-job
        namespace: "{{ meta.namespace }}"
      spec: "{{ job_spec }}"


