- name: test if host is defined
  fail:
    msg: 'the key host not defined'
  when: "host is not defined"
- name: test if namespace is defined
  fail:
    msg: 'the key namespace not defined'
  when: "namespace is not defined"
- name: "read host {{ host }} resource"
  k8s_facts:
    api_version: postgres.kabisa.nl/v1alpha1
    kind: PostgresHost
    namespace: "{{ namespace }}"
    name: "{{ host }}"
  register: host_cr
- fail:
    msg: 'host "{{ host }}" not found'
  when: "host_cr.resources | length == 0"
- name: "read host {{ host }}"
  k8s_facts:
    kind: Secret
    namespace: "{{ namespace }}"
    name: "{{ host_cr.resources[0].spec.secret_name }}"
  register: host_secret
- fail:
    msg: 'secret "{{ host_cr.resources[0].spec.secret_name  }}" not found'
  when: "host_secret.resources | length != 1"
- name: debug
  debug:
    var: host_secret
- name: get password key
  set_fact:
    get_host_info_password_key: '{{ host_cr.resources[0].spec.get("secret_key", "password") }}'
- fail:
    msg: 'the key "{{ get_host_info_password_key }}" is not available in secret "{{ host_cr.resources[0].spec.secret_name }}"'
  when: host_secret.resources[0].data[get_host_info_password_key] is not defined
- name: get vars
  set_fact:
    password: "{{ host_secret.resources[0].data[get_host_info_password_key] | b64decode }}"
    address: "{{ host_cr.resources[0].spec.address }}"
    port: "{{ host_cr.resources[0].spec.port }}"
    user_name: "{{ host_cr.resources[0].spec.user_name }}"
- name: update output
  set_fact:
     res_dict: "{{ res_dict | default({}) | combine( { res_key: {
        'password': password,
        'address': address,
        'port': port,
        'user_name': user_name
     }}, recursive=True ) }}"
  when: res_key is defined

