---
# tasks file for database
- name: "read host {{ host }} resource"
  k8s_info:
    api_version: postgres.kabisa.nl/v1alpha1
    kind: PostgresHost
    namespace: "{{ meta.namespace }}"
    name: "{{ host }}"
  register: host_cr
- name: get host info
  include_role:
    name: postgreshost
    tasks_from: get_info
  vars:
    host: "{{ host }}"
    namespace: "{{ meta.namespace }}"
- name: "Create a new database with name {{ database_name }}"
  postgresql_db:
    name: "{{ database_name }}"
    state: "{{ desired_state }}"
    login_user: "{{ admin_user_name }}"
    login_host: "{{ address }}"
    login_password: "{{ admin_password }}"
    port: "{{ port }}"
