apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: databasebackupcronjob.postgres.kabisa.nl
spec:
  group: postgres.kabisa.nl
  names:
    kind: DatabaseBackupCronJob
    listKind: DatabaseBackupCronJobs
    plural: databasebackupcronjob
    singular: databasebackupcronjob
  scope: Namespaced
  subresources:
    status: {}
  version: v1alpha1
  validation:
    openAPIV3Schema:
      required: ["spec"]
      properties:
        spec:
          required: ["database_name", "cron_interval"]
          properties:
            database_name:
              type: string
              minimum: 1
            cron_interval:
              type: string
              minimum: 1
            # not required so that in the future we could allow for other methods
            az_blobs_container:
              type: string
            az_blobs_user:
              type: string
