apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: databases.postgres.kabisa.nl
spec:
  group: postgres.kabisa.nl
  names:
    kind: Database
    listKind: DatabaseList
    plural: databases
    singular: database
  scope: Namespaced
  subresources:
    status: {}
  versions:
  - name: v1alpha1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        required: ["spec"]
        properties:
          spec:
            required: ["host" , "database"]
            properties:
              host:
                type: string
                minimum: 1
              database_name:
                type: string
                minimum: 1
