apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: databasecopyjob.postgres.kabisa.nl
spec:
  group: postgres.kabisa.nl
  names:
    kind: DatabaseCopyJob
    listKind: DatabaseCopyJobs
    plural: databasecopyjob
    singular: databasecopyjob
  scope: Namespaced
  subresources:
    status: {}
  version: v1alpha1
  validation:
    openAPIV3Schema:
      required: ["spec"]
      properties:
        spec:
          required: ["from_database_name", "to_database_name"]
          properties:
            from_database_name:
              type: string
              minimum: 1
            to_database_name:
              type: string
              minimum: 1
            after_action_sql:
              type: string