apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: postgresusergrants.postgres.kabisa.nl
spec:
  group: postgres.kabisa.nl
  names:
    kind: PostgresUserGrant
    listKind: PostgresUserGrantList
    plural: postgresusergrants
    singular: postgresusergrant
  scope: Namespaced
  subresources:
    status: {}
  version: v1alpha1
  validation:
    openAPIV3Schema:
      required: ["spec"]
      properties:
        spec:
          required: ["user_name", "database_name", "priv"]
          properties:
            user_name:
              type: string
              minimum: 1
            database_name:
              type: string
              minimum: 1
            priv:
              type: string
              minimum: 1
