apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: azblobsusers.postgres.kabisa.nl
spec:
  group: postgres.kabisa.nl
  names:
    kind: AzBlobsUser
    listKind: AzBlobsUserList
    plural: azblobsusers
    singular: azblobsuser
  scope: Namespaced
  subresources:
    status: {}
  version: v1alpha1
  validation:
    openAPIV3Schema:
      required: ["spec"]
      properties:
        spec:
          required: ["user_name", "secret_name"]
          properties:
            user_name:
              type: string
              minimum: 1
            secret_name:
              type: string
              minimum: 1
