apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: databases.postgres.kabisa.nl
spec:
  group: postgres.kabisa.nl
  names:
    kind: Database
    listKind: DatabaseList
    plural: databases
    singular: database
  scope: Namespaced
  subresources:
    status: {}
  version: v1alpha1
  validation:
    openAPIV3Schema:
      required: ["spec"]
      properties:
        spec:
          required: ["host" , "database_name", "drop_on_deletion"]
          properties:
            host:
              type: string
              minimum: 1
            database_name:
              type: string
              minimum: 1
            drop_on_deletion:
              type: boolean
