apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: postgresusers.postgres.kabisa.nl
spec:
  group: postgres.kabisa.nl
  names:
    kind: PostgresUser
    listKind: PostgresUserList
    plural: postgresusers
    singular: postgresuser
  scope: Namespaced
  subresources:
    status: {}
  version: v1alpha1
  validation:
    openAPIV3Schema:
      required: ["spec"]
      properties:
        spec:
          required: ["user_name", "secret_name", "priv", "database_name"]
          properties:
            user_name:
              type: string
              minimum: 1
            secret_name:
              type: string
              minimum: 1
            priv:
              type: string
              minimum: 1
            database_name:
              type: string
              minimum: 1
