---
- name: create backup job
  include_role:
    name: jobs
    tasks_from: backup
  vars:
    job_type: job
    job_action: backup
  when: desired_state == "present"
- name: remove backup job
  include_role:
    name: jobs
    tasks_from: remove_job
  vars:
    job_type: job
    job_action: backup
  when: desired_state != "present"